// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyGamingMap.API.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MyGamingMap.API.Migrations
{
    [DbContext(typeof(MyGamingMapContext))]
    [Migration("20260806192550_AddFailedLookup")]
    partial class AddFailedLookup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CollectionGame", b =>
                {
                    b.Property<long>("CollectionsId")
                        .HasColumnType("bigint")
                        .HasColumnName("collections_id");

                    b.Property<long>("GamesIGDBId")
                        .HasColumnType("bigint")
                        .HasColumnName("games_igdb_id");

                    b.HasKey("CollectionsId", "GamesIGDBId")
                        .HasName("pk_collection_game");

                    b.HasIndex("GamesIGDBId")
                        .HasDatabaseName("ix_collection_game_games_igdb_id");

                    b.ToTable("collection_game", (string)null);
                });

            modelBuilder.Entity("FranchiseGame", b =>
                {
                    b.Property<long>("FranchisesId")
                        .HasColumnType("bigint")
                        .HasColumnName("franchises_id");

                    b.Property<long>("GamesIGDBId")
                        .HasColumnType("bigint")
                        .HasColumnName("games_igdb_id");

                    b.HasKey("FranchisesId", "GamesIGDBId")
                        .HasName("pk_franchise_game");

                    b.HasIndex("GamesIGDBId")
                        .HasDatabaseName("ix_franchise_game_games_igdb_id");

                    b.ToTable("franchise_game", (string)null);
                });

            modelBuilder.Entity("GameGameEngine", b =>
                {
                    b.Property<long>("GameEnginesId")
                        .HasColumnType("bigint")
                        .HasColumnName("game_engines_id");

                    b.Property<long>("GamesIGDBId")
                        .HasColumnType("bigint")
                        .HasColumnName("games_igdb_id");

                    b.HasKey("GameEnginesId", "GamesIGDBId")
                        .HasName("pk_game_game_engine");

                    b.HasIndex("GamesIGDBId")
                        .HasDatabaseName("ix_game_game_engine_games_igdb_id");

                    b.ToTable("game_game_engine", (string)null);
                });

            modelBuilder.Entity("GameGameMode", b =>
                {
                    b.Property<long>("GameModesId")
                        .HasColumnType("bigint")
                        .HasColumnName("game_modes_id");

                    b.Property<long>("GamesIGDBId")
                        .HasColumnType("bigint")
                        .HasColumnName("games_igdb_id");

                    b.HasKey("GameModesId", "GamesIGDBId")
                        .HasName("pk_game_game_mode");

                    b.HasIndex("GamesIGDBId")
                        .HasDatabaseName("ix_game_game_mode_games_igdb_id");

                    b.ToTable("game_game_mode", (string)null);
                });

            modelBuilder.Entity("GameGenre", b =>
                {
                    b.Property<long>("GamesIGDBId")
                        .HasColumnType("bigint")
                        .HasColumnName("games_igdb_id");

                    b.Property<long>("GenresId")
                        .HasColumnType("bigint")
                        .HasColumnName("genres_id");

                    b.HasKey("GamesIGDBId", "GenresId")
                        .HasName("pk_game_genre");

                    b.HasIndex("GenresId")
                        .HasDatabaseName("ix_game_genre_genres_id");

                    b.ToTable("game_genre", (string)null);
                });

            modelBuilder.Entity("GamePlayerPerspective", b =>
                {
                    b.Property<long>("GamesIGDBId")
                        .HasColumnType("bigint")
                        .HasColumnName("games_igdb_id");

                    b.Property<long>("PlayerPerspectivesId")
                        .HasColumnType("bigint")
                        .HasColumnName("player_perspectives_id");

                    b.HasKey("GamesIGDBId", "PlayerPerspectivesId")
                        .HasName("pk_game_player_perspective");

                    b.HasIndex("PlayerPerspectivesId")
                        .HasDatabaseName("ix_game_player_perspective_player_perspectives_id");

                    b.ToTable("game_player_perspective", (string)null);
                });

            modelBuilder.Entity("GameTheme", b =>
                {
                    b.Property<long>("GamesIGDBId")
                        .HasColumnType("bigint")
                        .HasColumnName("games_igdb_id");

                    b.Property<long>("ThemesId")
                        .HasColumnType("bigint")
                        .HasColumnName("themes_id");

                    b.HasKey("GamesIGDBId", "ThemesId")
                        .HasName("pk_game_theme");

                    b.HasIndex("ThemesId")
                        .HasDatabaseName("ix_game_theme_themes_id");

                    b.ToTable("game_theme", (string)null);
                });

            modelBuilder.Entity("MyGamingMap.API.Models.Entities.Collection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_collections");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_collections_name");

                    b.ToTable("collections", (string)null);
                });

            modelBuilder.Entity("MyGamingMap.API.Models.Entities.Company", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("LogoImageId")
                        .HasColumnType("text")
                        .HasColumnName("logo_image_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_companies");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_companies_name");

                    b.ToTable("companies", (string)null);
                });

            modelBuilder.Entity("MyGamingMap.API.Models.Entities.FailedLookup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset>("FirstAttempt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_attempt");

                    b.Property<DateTimeOffset>("LastAttempt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_attempt");

                    b.Property<string>("NormalisedName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("normalised_name");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("platform");

                    b.HasKey("Id")
                        .HasName("pk_failed_lookups");

                    b.HasIndex("NormalisedName", "Platform")
                        .IsUnique()
                        .HasDatabaseName("ix_failed_lookups_normalised_name_platform");

                    b.ToTable("failed_lookups", (string)null);
                });

            modelBuilder.Entity("MyGamingMap.API.Models.Entities.Franchise", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_franchises");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_franchises_name");

                    b.ToTable("franchises", (string)null);
                });

            modelBuilder.Entity("MyGamingMap.API.Models.Entities.Game", b =>
                {
                    b.Property<long>("IGDBId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("igdb_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IGDBId"));

                    b.Property<string>("CoverId")
                        .HasColumnType("text")
                        .HasColumnName("cover_id");

                    b.Property<string>("ESRB_Rating")
                        .HasColumnType("text")
                        .HasColumnName("esrb_rating");

                    b.Property<long?>("GameTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("game_type_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int?>("PEGI_Rating")
                        .HasColumnType("integer")
                        .HasColumnName("pegi_rating");

                    b.Property<int?>("ReviewCount")
                        .HasColumnType("integer")
                        .HasColumnName("review_count");

                    b.Property<double?>("ReviewRating")
                        .HasColumnType("double precision")
                        .HasColumnName("review_rating");

                    b.Property<string>("Storyline")
                        .HasColumnType("text")
                        .HasColumnName("storyline");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("IGDBId")
                        .HasName("pk_games");

                    b.HasIndex("GameTypeId")
                        .HasDatabaseName("ix_games_game_type_id");

                    b.ToTable("games", (string)null);
                });

            modelBuilder.Entity("MyGamingMap.API.Models.Entities.GameEngine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("LogoImageId")
                        .HasColumnType("text")
                        .HasColumnName("logo_image_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_game_engines");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_game_engines_name");

                    b.ToTable("game_engines", (string)null);
                });

            modelBuilder.Entity("MyGamingMap.API.Models.Entities.GameMapping", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("ConceptId")
                        .HasColumnType("integer")
                        .HasColumnName("concept_id");

                    b.Property<long>("IGDBId")
                        .HasColumnType("bigint")
                        .HasColumnName("igdb_id");

                    b.Property<string>("NpCommunicationId")
                        .HasColumnType("text")
                        .HasColumnName("np_communication_id");

                    b.HasKey("Id")
                        .HasName("pk_game_mappings");

                    b.HasIndex("ConceptId")
                        .HasDatabaseName("ix_game_mappings_concept_id");

                    b.HasIndex("IGDBId")
                        .HasDatabaseName("ix_game_mappings_igdb_id");

                    b.HasIndex("NpCommunicationId")
                        .HasDatabaseName("ix_game_mappings_np_communication_id");

                    b.ToTable("game_mappings", (string)null);
                });

            modelBuilder.Entity("MyGamingMap.API.Models.Entities.GameMode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_game_modes");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_game_modes_name");

                    b.ToTable("game_modes", (string)null);
                });

            modelBuilder.Entity("MyGamingMap.API.Models.Entities.GameType", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_game_types");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_game_types_name");

                    b.ToTable("game_types", (string)null);
                });

            modelBuilder.Entity("MyGamingMap.API.Models.Entities.Genre", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_genres");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_genres_name");

                    b.ToTable("genres", (string)null);
                });

            modelBuilder.Entity("MyGamingMap.API.Models.Entities.InvolvedCompany", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint")
                        .HasColumnName("company_id");

                    b.Property<bool>("Developer")
                        .HasColumnType("boolean")
                        .HasColumnName("developer");

                    b.Property<long>("GameId")
                        .HasColumnType("bigint")
                        .HasColumnName("game_id");

                    b.Property<bool>("Publisher")
                        .HasColumnType("boolean")
                        .HasColumnName("publisher");

                    b.HasKey("Id")
                        .HasName("pk_involved_companies");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_involved_companies_company_id");

                    b.HasIndex("GameId")
                        .HasDatabaseName("ix_involved_companies_game_id");

                    b.ToTable("involved_companies", (string)null);
                });

            modelBuilder.Entity("MyGamingMap.API.Models.Entities.PlayerPerspective", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_player_perspectives");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_player_perspectives_name");

                    b.ToTable("player_perspectives", (string)null);
                });

            modelBuilder.Entity("MyGamingMap.API.Models.Entities.Region", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_regions");

                    b.ToTable("regions", (string)null);
                });

            modelBuilder.Entity("MyGamingMap.API.Models.Entities.ReleaseDate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<long>("GameIGDBId")
                        .HasColumnType("bigint")
                        .HasColumnName("game_igdb_id");

                    b.Property<string>("Platform")
                        .HasColumnType("text")
                        .HasColumnName("platform");

                    b.Property<long?>("RegionId")
                        .HasColumnType("bigint")
                        .HasColumnName("region_id");

                    b.HasKey("Id")
                        .HasName("pk_release_dates");

                    b.HasIndex("GameIGDBId")
                        .HasDatabaseName("ix_release_dates_game_igdb_id");

                    b.HasIndex("RegionId")
                        .HasDatabaseName("ix_release_dates_region_id");

                    b.ToTable("release_dates", (string)null);
                });

            modelBuilder.Entity("MyGamingMap.API.Models.Entities.Screenshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("GameId")
                        .HasColumnType("bigint")
                        .HasColumnName("game_id");

                    b.Property<string>("ImageId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image_id");

                    b.HasKey("Id")
                        .HasName("pk_screenshots");

                    b.HasIndex("GameId")
                        .HasDatabaseName("ix_screenshots_game_id");

                    b.ToTable("screenshots", (string)null);
                });

            modelBuilder.Entity("MyGamingMap.API.Models.Entities.Theme", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_themes");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_themes_name");

                    b.ToTable("themes", (string)null);
                });

            modelBuilder.Entity("CollectionGame", b =>
                {
                    b.HasOne("MyGamingMap.API.Models.Entities.Collection", null)
                        .WithMany()
                        .HasForeignKey("CollectionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_collection_game_collections_collections_id");

                    b.HasOne("MyGamingMap.API.Models.Entities.Game", null)
                        .WithMany()
                        .HasForeignKey("GamesIGDBId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_collection_game_games_games_igdb_id");
                });

            modelBuilder.Entity("FranchiseGame", b =>
                {
                    b.HasOne("MyGamingMap.API.Models.Entities.Franchise", null)
                        .WithMany()
                        .HasForeignKey("FranchisesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_franchise_game_franchises_franchises_id");

                    b.HasOne("MyGamingMap.API.Models.Entities.Game", null)
                        .WithMany()
                        .HasForeignKey("GamesIGDBId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_franchise_game_games_games_igdb_id");
                });

            modelBuilder.Entity("GameGameEngine", b =>
                {
                    b.HasOne("MyGamingMap.API.Models.Entities.GameEngine", null)
                        .WithMany()
                        .HasForeignKey("GameEnginesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_game_game_engine_game_engines_game_engines_id");

                    b.HasOne("MyGamingMap.API.Models.Entities.Game", null)
                        .WithMany()
                        .HasForeignKey("GamesIGDBId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_game_game_engine_games_games_igdb_id");
                });

            modelBuilder.Entity("GameGameMode", b =>
                {
                    b.HasOne("MyGamingMap.API.Models.Entities.GameMode", null)
                        .WithMany()
                        .HasForeignKey("GameModesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_game_game_mode_game_modes_game_modes_id");

                    b.HasOne("MyGamingMap.API.Models.Entities.Game", null)
                        .WithMany()
                        .HasForeignKey("GamesIGDBId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_game_game_mode_games_games_igdb_id");
                });

            modelBuilder.Entity("GameGenre", b =>
                {
                    b.HasOne("MyGamingMap.API.Models.Entities.Game", null)
                        .WithMany()
                        .HasForeignKey("GamesIGDBId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_game_genre_games_games_igdb_id");

                    b.HasOne("MyGamingMap.API.Models.Entities.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_game_genre_genres_genres_id");
                });

            modelBuilder.Entity("GamePlayerPerspective", b =>
                {
                    b.HasOne("MyGamingMap.API.Models.Entities.Game", null)
                        .WithMany()
                        .HasForeignKey("GamesIGDBId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_game_player_perspective_games_games_igdb_id");

                    b.HasOne("MyGamingMap.API.Models.Entities.PlayerPerspective", null)
                        .WithMany()
                        .HasForeignKey("PlayerPerspectivesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_game_player_perspective_player_perspectives_player_perspect");
                });

            modelBuilder.Entity("GameTheme", b =>
                {
                    b.HasOne("MyGamingMap.API.Models.Entities.Game", null)
                        .WithMany()
                        .HasForeignKey("GamesIGDBId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_game_theme_games_games_igdb_id");

                    b.HasOne("MyGamingMap.API.Models.Entities.Theme", null)
                        .WithMany()
                        .HasForeignKey("ThemesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_game_theme_themes_themes_id");
                });

            modelBuilder.Entity("MyGamingMap.API.Models.Entities.Game", b =>
                {
                    b.HasOne("MyGamingMap.API.Models.Entities.GameType", "GameType")
                        .WithMany("Games")
                        .HasForeignKey("GameTypeId")
                        .HasConstraintName("fk_games_game_types_game_type_id");

                    b.Navigation("GameType");
                });

            modelBuilder.Entity("MyGamingMap.API.Models.Entities.GameMapping", b =>
                {
                    b.HasOne("MyGamingMap.API.Models.Entities.Game", "Game")
                        .WithMany("Mappings")
                        .HasForeignKey("IGDBId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_game_mappings_games_igdb_id");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("MyGamingMap.API.Models.Entities.InvolvedCompany", b =>
                {
                    b.HasOne("MyGamingMap.API.Models.Entities.Company", "Company")
                        .WithMany("InvolvedCompanies")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_involved_companies_companies_company_id");

                    b.HasOne("MyGamingMap.API.Models.Entities.Game", "Game")
                        .WithMany("InvolvedCompanies")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_involved_companies_games_game_id");

                    b.Navigation("Company");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("MyGamingMap.API.Models.Entities.ReleaseDate", b =>
                {
                    b.HasOne("MyGamingMap.API.Models.Entities.Game", "Game")
                        .WithMany("ReleaseDates")
                        .HasForeignKey("GameIGDBId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_release_dates_games_game_igdb_id");

                    b.HasOne("MyGamingMap.API.Models.Entities.Region", "Region")
                        .WithMany("ReleaseDates")
                        .HasForeignKey("RegionId")
                        .HasConstraintName("fk_release_dates_regions_region_id");

                    b.Navigation("Game");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("MyGamingMap.API.Models.Entities.Screenshot", b =>
                {
                    b.HasOne("MyGamingMap.API.Models.Entities.Game", "Game")
                        .WithMany("Screenshots")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_screenshots_games_game_id");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("MyGamingMap.API.Models.Entities.Company", b =>
                {
                    b.Navigation("InvolvedCompanies");
                });

            modelBuilder.Entity("MyGamingMap.API.Models.Entities.Game", b =>
                {
                    b.Navigation("InvolvedCompanies");

                    b.Navigation("Mappings");

                    b.Navigation("ReleaseDates");

                    b.Navigation("Screenshots");
                });

            modelBuilder.Entity("MyGamingMap.API.Models.Entities.GameType", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("MyGamingMap.API.Models.Entities.Region", b =>
                {
                    b.Navigation("ReleaseDates");
                });
#pragma warning restore 612, 618
        }
    }
}
